export const CATEGORIES = [
  { icon: 'md-briefcase', name: 'Trabajo' },
  { icon: 'md-home', name: 'Hogar' },
  { icon: 'md-basket', name: 'Compras' },
  { icon: 'md-school', name: 'Escuela' },
  { icon: 'md-fitness', name: 'Ejercicio' },
  { icon: 'md-medkit', name: 'Salud' },
  { icon: 'md-car', name: 'Carro' },
  { icon: 'md-restaurant', name: 'Comida' },
  { icon: 'md-film', name: 'Cine/TV' },
  { icon: 'md-bed', name: 'Descanso' },
  { icon: 'md-book', name: 'Lectura' },
  { icon: 'md-brush', name: 'Arte' },
  { icon: 'md-chatbox', name: 'Comunicación' },
  { icon: 'md-clipboard', name: 'Pendientes' },
  { icon: 'md-time', name: 'Tiempo' },
  { icon: 'md-compass', name: 'Exploración' },
  { icon: 'md-cut', name: 'Arreglo' },
  { icon: 'md-desktop', name: 'Tecnología' },
  { icon: 'md-eye', name: 'Vigilancia' },
  { icon: 'md-gift', name: 'Regalos' },
  { icon: 'md-leaf', name: 'Naturaleza' },
  { icon: 'md-musical-notes', name: 'Música' },
  { icon: 'md-nutrition', name: 'Nutrición' },
  { icon: 'md-paw', name: 'Mascotas' },
  { icon: 'md-people', name: 'Social' },
  { icon: 'md-shirt', name: 'Ropa' },
  { icon: 'md-star', name: 'Importante' },
  { icon: 'md-wallet', name: 'Dinero' },
  { icon: 'md-wine', name: 'Bebidas' },
];

export const COLORS = [
  '#EF5350',
  '#EC407A',
  '#AB47BC',
  '#7E57C2',
  '#5C6BC0',
  '#42A5F5',
  '#29B6F6',
  '#26C6DA',
  '#26A69A',
  '#66BB6A',
  '#9CCC65',
  '#FFA726',
  '#FF7043',
  '#8D6E63',
  '#78909C',
  '#FDD835',
];
